env:
  es6: true
  browser: false
  node: false
  amd: false
  mocha: false
  jasmine: false
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 9
  sourceType: module
rules:
  react/react-in-jsx-scope: 0
globals:
  __dirname: false
  __filename: false
  require: false
  module: false
  setTimeout: true
