env:
  es6: true
  browser: false
  node: false
  amd: false
  mocha: false
  jasmine: false
extends:
  - plugin:flowtype/recommended
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  import/no-unresolved: [2, {commonjs: true, amd: true}]
  import/no-extraneous-dependencies: 2
  import/named: 2
  import/namespace: 2
  import/export: 2
  import/order: 2
  inferno/jsx-uses-inferno: error
  inferno/jsx-uses-vars: error
  flowtype/define-flow-type: 1
  no-alert: 2
  no-array-constructor: 2
  no-bitwise: 0
  no-caller: 2
  no-catch-shadow: 2
  no-cond-assign: 2
  no-console: 2
  no-constant-condition: 2
  no-control-regex: 2
  no-debugger: 2
  no-delete-var: 2
  no-div-regex: 2
  no-dupe-keys: 2
  no-dupe-args: 2
  no-duplicate-case: 2
  no-else-return: 2
  no-empty: 2
  no-empty-character-class: 2
  no-eq-null: 2
  no-eval: 2
  no-ex-assign: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-boolean-cast: 2
  no-extra-semi: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  no-func-assign: 2
  no-implicit-coercion: 2
  no-implied-eval: 2
  no-inner-declarations:
  - 2
  - functions
  no-invalid-regexp: 2
  no-invalid-this: 2
  no-irregular-whitespace: 2
  no-iterator: 2
  no-label-var: 2
  no-labels: 2
  no-lone-blocks: 2
  no-lonely-if: 2
  no-loop-func: 2
  no-mixed-requires:
  - 2
  - false
  no-mixed-spaces-and-tabs:
  - 2
  - false
  linebreak-style:
  - 2
  - unix
  no-multi-spaces: 2
  no-multi-str: 2
  no-multiple-empty-lines:
  - 2
  - max: 1
  no-native-reassign: 2
  no-negated-in-lhs: 2
  no-nested-ternary: 0
  no-new: 2
  no-new-func: 2
  no-new-object: 2
  no-new-require: 2
  no-new-wrappers: 2
  no-obj-calls: 2
  no-octal: 2
  no-octal-escape: 2
  no-param-reassign: 0
  no-path-concat: 2
  no-plusplus: 0
  no-process-env: 2
  no-process-exit: 2
  no-proto: 2
  no-redeclare: 2
  no-regex-spaces: 2
  no-reserved-keys: 0
  no-restricted-modules: 0
  no-return-assign: 0
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-shadow: 0
  no-shadow-restricted-names: 2
  no-spaced-func: 2
  no-sparse-arrays: 2
  no-sync: 0
  no-ternary: 0
  no-trailing-spaces: 2
  no-throw-literal: 2
  no-undef: 2
  no-undef-init: 2
  no-undefined: 0
  no-unexpected-multiline: 2
  no-underscore-dangle: 0
  no-unneeded-ternary: 2
  no-unreachable: 2
  no-unused-expressions: 2
  no-unused-vars:
  - 2
  - vars: all
    args: none
  no-use-before-define:
  - 2
  - nofunc
  no-useless-call: 2
  no-void: 0
  no-warning-comments:
  - 0
  - terms:
    - todo
    - fixme
    - xxx
    location: start
  no-with: 2
  array-bracket-spacing:
  - 2
  - never
  block-spacing:
  - 2
  - always
  brace-style:
  - 2
  - 1tbs
  comma-dangle:
  - error
  - always-multiline
  comma-spacing:
  - 2
  - before: false
    after: true
  comma-style:
  - 2
  - last
  complexity:
  - 2
  - 11
  computed-property-spacing:
  - 2
  - never
  consistent-this:
  - 2
  - self
  curly:
  - 2
  - all
  default-case: 2
  dot-location:
  - 2
  - property
  dot-notation:
  - 2
  - allowKeywords: true
  eol-last: 2
  eqeqeq: 2
  func-names: 2
  guard-for-in: 2
  handle-callback-err:
  - 2
  - "^(err|error|anySpecificError)$"
  id-length: 0
  id-match: 0
  indent:
  - 2
  - 2
  init-declarations: 0
  key-spacing:
  - 2
  - beforeColon: false
    afterColon: true
  max-depth:
  - 2
  - 4
  max-len: 0
  max-nested-callbacks:
  - 2
  - 3
  max-params:
  - 2
  - 5
  new-cap:
  - 2
  - newIsCap: true
    capIsNew: false
  new-parens: 2
  newline-after-var: 0
  object-curly-spacing:
  - 2
  - never
  one-var:
  - 2
  - never
  operator-assignment:
  - 0
  - always
  operator-linebreak:
  - 2
  - after
  padded-blocks: 0
  radix: 2
  semi:
  - 2
  - always
  semi-spacing:
  - 2
  - before: false
    after: true
  sort-vars: 0
  keyword-spacing:
  - 2
  space-before-blocks:
  - 2
  - always
  space-before-function-paren:
  - 2
  - never
  space-in-parens:
  - 2
  - never
  space-infix-ops: 2
  space-unary-ops:
  - 2
  - words: true
    nonwords: false
  spaced-comment:
  - 2
  - always
  - exceptions:
    - "-"
    - "="
    - "+"
    - "*"
  strict:
  - 2
  - global
  use-isnan: 2
  valid-jsdoc:
  - 2
  - requireReturn: false
    requireParamDescription: false
  valid-typeof: 2
  vars-on-top: 0
  wrap-iife: 2
  wrap-regex: 0
  yoda:
  - 2
  - never
  block-scoped-var: 0
  no-extra-parens: 0
  camelcase: 0
  jsx-quotes:
  - 2
  - prefer-single
  quotes:
  - 2
  - single
  - avoid-escape
  no-class-assign: 2
  no-const-assign: 2
  no-continue: 2
  no-dupe-class-members: 2
  no-this-before-super: 2
  no-var: 2
  prefer-arrow-callback: 0
  prefer-const: 2
  prefer-reflect: 0
  prefer-spread: 2
  prefer-template: 2
  arrow-parens:
  - 2
  - as-needed
  arrow-spacing:
  - 2
  - before: true
    after: true
  accessor-pairs:
  - 2
  - getWithoutSet: true
  constructor-super: 2
  func-style:
  - 2
  - declaration
  generator-star-spacing:
  - 2
  - before: false
    after: true
  lines-around-comment:
  - 0
  - beforeBlockComment: true
    afterBlockComment: false
    beforeLineComment: false
    afterLineComment: false
    allowBlockStart: true
    allowBlockEnd: true
  max-statements:
  - 2
  - 15
  object-shorthand:
  - 2
  - always
  quote-props:
  - 2
  - as-needed
  require-yield: 2
plugins:
  - inferno
  - flowtype
  - import
parser: babel-eslint
globals:
  __dirname: false
  __filename: false
  require: false
  module: false
