struct GetAddressIdRequest {
  id string
}

struct GetAddressIdResponse {
  address      string
  totalBalance int
  nonce        int
  pendingNonce int
  isCandidate  bool
}

struct RawTransaction {
  amount   int
  byteCode string
  nonce    int
  gasLimit string
  version  int
  // contract address
  contract string
}

struct SignedTransaction {
  version        int
  nonce          int
  signature      string
  executor       string
  contract       string
  executorPubKey string
  gas            int
  gasPrice       int
  data           string
  ID             string
  amount         int
  blockID        string
  isPending      bool
  timestamp      int
}

struct Execution {
  version int
  ID string
  nonce int
  executor string
  contract string
  amount int
  executorPubKey string
  signature string
  gas int
  gasPrice int
  timestamp int
  data string
  blockID string
  isPending bool
}

struct Wallet {
  publicKey  string
  privateKey string
  rawAddress string
}

struct SignContractAbiRequest {
  rawTransaction RawTransaction
  wallet Wallet
}

struct SignContractAbiResponse {
  signedTransaction SignedTransaction
}

struct SendTransactionRequest {
  type              string
  signedTransaction SignedTransaction
}

struct SendTransactionResponse {
  hash string
}

struct Receipt {
  returnValue     string
  status          int
  hash            string
  gasConsumed     int
  contractAddress string
  logs            []Log
}

struct Log {
  address     string
  topics      []string
  data        string
  blockNumber int
  txnHash     string
  blockHash   string
  index       int
}

interface JsonRpc {
  getAddressId(request GetAddressIdRequest) GetAddressIdResponse
  signContractAbi(request SignContractAbiRequest) SignContractAbiResponse
  sendTransaction(request SendTransactionRequest) SendTransactionResponse
  getReceiptByExecutionId(id string) Receipt
  readExecutionState(request Execution) string
}
